# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d1c996fad63cc7a2befd2e316abac10e66e0ddd8dbded22940d42a25b6d5c09a7e964dea4f3be2d7e7d87026508cc822b8e210f5b70da8dea55c2e69de57ae1

test:
  secret_key_base: 7fc6f51c110b56362663e019d6eed99feb64dbd7277a6eacd96b96989361770486ddf33d517c86fc4bea3ab247fa20f7037059514095f478f09297629bbe9553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
